sonar.verbose=true
sonar.organization=manusonar-01
sonar.projectKey=manusonar-01_manuproject
sonar.projectName=manuproject
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

